CREATE TABLE ED000PR (
    CUSNO  NUMBER(8, 0)   NOT NULL,
    SHPNO  NUMBER(2, 0)   NOT NULL,
    PRTNO  VARCHAR2(15)   NOT NULL,
    DUEDT  NUMBER(8, 0)   NOT NULL,
    CORNO  VARCHAR2(20)       NOT NULL,
    CPRTN  VARCHAR2(20)       NOT NULL,
    OGQTY  NUMBER(7, 0)   NOT NULL,
    ORQTY  NUMBER(7, 0)   NOT NULL,
    ALQTY  NUMBER(7, 0)   NOT NULL,
    SHDQY  NUMBER(7, 0)   NOT NULL,
    SHPDT  NUMBER(8, 0)   NOT NULL,
    NOSHP  NUMBER(3, 0)   NOT NULL,
    KBFLG  NUMBER(1, 0)   NOT NULL,
    ODRFL  NUMBER(1, 0)   NOT NULL,
    SORNO  VARCHAR2(10)       NOT NULL,
    SPODF  VARCHAR2(1)        NOT NULL,
    MODEL  VARCHAR2(15)       NOT NULL,
    CUSPO  VARCHAR2(60)       NOT NULL,
    LOTNO  VARCHAR2(60)       NOT NULL,
    LMNDT  NUMBER(8, 0)   NOT NULL,
	REGISTERED_AT	DATE	NOT NULL,
	REGISTERED_COMPNAME	VARCHAR2(50)	NOT NULL,
	REGISTERED_COMPCODE	VARCHAR2(50)	NOT NULL
);

CREATE TABLE EDT01PR (
    CUSNO                 NUMBER(8, 0)     NOT NULL,
    SHPNO                 NUMBER(2, 0)     NOT NULL,
    MODEL                 VARCHAR2(15)         NOT NULL,
    DUEDT                 NUMBER(8, 0)     NOT NULL,
    CORNO                 VARCHAR2(20)         NOT NULL,
    CUSPO                 VARCHAR2(60)         NOT NULL,
    LOTNO                 VARCHAR2(60)         NOT NULL,
    ORQTY                 NUMBER(7, 0)     NOT NULL,
    OQFLG                 VARCHAR2(1)          NOT NULL,
    MPFLG                 VARCHAR2(1)          NOT NULL,
    CFMNO                 VARCHAR2(20)         NOT NULL,
    REGISTERED_AT         DATE             NOT NULL,
    REGISTERED_COMPNAME   VARCHAR2(50)     NOT NULL,
    REGISTERED_COMPCODE   VARCHAR2(50)     NOT NULL
);

CREATE TABLE ED005PR (
    TRKNO                 NUMBER(7, 0)     NOT NULL,
    CUSNO                 NUMBER(8, 0)     NOT NULL,
    SHPNO                 NUMBER(2, 0)     NOT NULL,
    PRTNO                 VARCHAR2(15)         NOT NULL,
    DUEDT                 NUMBER(8, 0)     NOT NULL,
    CORNO                 VARCHAR2(20)         NOT NULL,
    CPRTN                 VARCHAR2(20)         NOT NULL,
    SHPQY                 NUMBER(7, 0)     NOT NULL,
    SHDQY                 NUMBER(7, 0)     NOT NULL,
    SORNO                 VARCHAR2(10)         NOT NULL,
    QTUNT                 NUMBER(7, 0)     NOT NULL,
    UNMSR                 VARCHAR2(2)          NOT NULL,
    UNMDC                 VARCHAR2(3)          NOT NULL,
    CPDSC                 VARCHAR2(25)         NOT NULL,
    ITCLS                 VARCHAR2(2)          NOT NULL,
    HOUSE                 VARCHAR2(1)          NOT NULL,
    WHSLC                 VARCHAR2(5)          NOT NULL,
    REGISTERED_AT         DATE             NOT NULL,
    REGISTERED_COMPNAME   VARCHAR2(50)     NOT NULL,
    REGISTERED_COMPCODE   VARCHAR2(50)     NOT NULL
);


CREATE TABLE EDT31PR (
    CUSNO                 NUMBER(8, 0)     NOT NULL,
    SHPNO                 NUMBER(2, 0)     NOT NULL,
    CUSPO                 VARCHAR2(20)         NOT NULL,
    ODUED                 NUMBER(8, 0)     NOT NULL,
    DUEDT                 NUMBER(8, 0)     NOT NULL,
    ODUET                 NUMBER(6, 0)     NOT NULL,
    DUETM                 NUMBER(6, 0)     NOT NULL,
    MODEL                 VARCHAR2(10)         NOT NULL,
    CPRTN                 VARCHAR2(20)         NOT NULL,
    CPTYP                 VARCHAR2(1)          NOT NULL,
    CPDSC                 VARCHAR2(30)         NOT NULL,
    OSHFT                 VARCHAR2(2)          NOT NULL,
    SHIFT                 VARCHAR2(2)          NOT NULL,
    OLOTN                 VARCHAR2(140)        NOT NULL,
    LOTNO                 VARCHAR2(140)        NOT NULL,
    PRCDT                 NUMBER(8, 0)     NOT NULL,
    PROCS                 VARCHAR2(10)         NOT NULL,
    RCLOC                 VARCHAR2(10)         NOT NULL,
    WHLOC                 VARCHAR2(10)         NOT NULL,
    GATE                  VARCHAR2(5)          NOT NULL,
    PILOT                 VARCHAR2(30)         NOT NULL,
    ECNNO                 VARCHAR2(10)         NOT NULL,
    BOXTP                 VARCHAR2(5)          NOT NULL,
    NOBOX                 NUMBER(3, 0)     NOT NULL,
    SHQTY                 NUMBER(7, 0)     NOT NULL,
    COLOR                 VARCHAR2(3)          NOT NULL,
    SUPCD                 VARCHAR2(6)          NOT NULL,
    SUPNM                 VARCHAR2(30)         NOT NULL,
    SBSUP                 VARCHAR2(6)          NOT NULL,
    LOTSZ                 NUMBER(5, 0)     NOT NULL,
    STRSQ                 NUMBER(5, 0)     NOT NULL,
    SBPRT                 VARCHAR2(14)         NOT NULL,
    ECNTG                 VARCHAR2(1)          NOT NULL,
    PILTG                 VARCHAR2(1)          NOT NULL,
    REVID                 VARCHAR2(10)         NOT NULL,
    FLLR1                 VARCHAR2(15)         NOT NULL,
    RSVF0                 VARCHAR2(10)         NOT NULL,
    RSVF1                 VARCHAR2(10)         NOT NULL,
    RSVF2                 VARCHAR2(15)         NOT NULL,
    RSVF3                 VARCHAR2(15)         NOT NULL,
    RSVF4                 VARCHAR2(15)         NOT NULL,
    RSVF5                 VARCHAR2(15)         NOT NULL,
    RSVF6                 VARCHAR2(15)         NOT NULL,
    RSVF7                 VARCHAR2(15)         NOT NULL,
    RSVF8                 VARCHAR2(15)         NOT NULL,
    RSVF9                 VARCHAR2(15)         NOT NULL,
    RSVF10                VARCHAR2(15)         NOT NULL,
    REGISTERED_AT         DATE             NOT NULL,
    REGISTERED_COMPNAME   VARCHAR2(50)     NOT NULL,
    REGISTERED_COMPCODE   VARCHAR2(50)     NOT NULL
);


CREATE TABLE ED004PR (
    TRKNO                 NUMBER(7, 0)     NOT NULL,
    CUSNO                 NUMBER(8, 0)     NOT NULL,
    SHPNO                 NUMBER(2, 0)     NOT NULL,
    SHPDT                 NUMBER(8, 0)     NOT NULL,
    PRFLG                 NUMBER(1, 0)     NOT NULL,
    DAFLG                 NUMBER(1, 0)     NOT NULL,
    NCINV                 NUMBER(1, 0)     NOT NULL,
    INVRF                 NUMBER(6, 0)     NOT NULL,
    INVFL                 NUMBER(1, 0)     NOT NULL,
    DDFLG                 NUMBER(1, 0)     NOT NULL,
    CMRFL                 NUMBER(1, 0)     NOT NULL,
    SIVFL                 NUMBER(1, 0)     NOT NULL,
    SDDFL                 NUMBER(1, 0)     NOT NULL,
    ISSDT                 NUMBER(8, 0)     NOT NULL,
    INVNO                 NUMBER(6, 0)     NOT NULL,
    DDNBR                 NUMBER(6, 0)     NOT NULL,
    SHDDT                 NUMBER(8, 0)     NOT NULL,
    ESTDA                 NUMBER(8, 0)     NOT NULL,
    ESTTA                 NUMBER(4, 0)     NOT NULL,
    SHPNM                 VARCHAR2(30)         NOT NULL,
    SHPA1                 VARCHAR2(25)         NOT NULL,
    SHPA2                 VARCHAR2(25)         NOT NULL,
    SHPA3                 VARCHAR2(25)         NOT NULL,
    SHPCT                 VARCHAR2(3)          NOT NULL,
    SHPAA                 VARCHAR2(10)         NOT NULL,
    SHPTP                 VARCHAR2(10)         NOT NULL,
    PACKG                 VARCHAR2(10)         NOT NULL,
    CARQY                 NUMBER(7, 0)     NOT NULL,
    PALQY                 NUMBER(7, 0)     NOT NULL,
    GWGHT                 NUMBER(9, 3)     NOT NULL,
    NWGHT                 NUMBER(9, 3)     NOT NULL,
    WGTUM                 VARCHAR2(2)          NOT NULL,
    WGTDC                 VARCHAR2(3)          NOT NULL,
    VOLUM                 NUMBER(7, 0)     NOT NULL,
    SHPMK                 VARCHAR2(10)         NOT NULL,
    UNLOC                 VARCHAR2(20)         NOT NULL,
    CARNM                 VARCHAR2(30)         NOT NULL,
    CARA1                 VARCHAR2(25)         NOT NULL,
    CARA2                 VARCHAR2(25)         NOT NULL,
    CARA3                 VARCHAR2(25)         NOT NULL,
    SINFO                 VARCHAR2(30)         NOT NULL,
    SNDNM                 VARCHAR2(30)         NOT NULL,
    SNDA1                 VARCHAR2(25)         NOT NULL,
    SNDA2                 VARCHAR2(25)         NOT NULL,
    SNDA3                 VARCHAR2(25)         NOT NULL,
    SNDCT                 VARCHAR2(3)          NOT NULL,
    SNDAA                 VARCHAR2(10)         NOT NULL,
    BILNO                 NUMBER(8, 0)     NOT NULL,
    BILNM                 VARCHAR2(30)         NOT NULL,
    BILA1                 VARCHAR2(25)         NOT NULL,
    BILA2                 VARCHAR2(25)         NOT NULL,
    BILA3                 VARCHAR2(25)         NOT NULL,
    BILCT                 VARCHAR2(3)          NOT NULL,
    BILAA                 VARCHAR2(10)         NOT NULL,
    BILNC                 VARCHAR2(20)         NOT NULL,
    BILDP                 VARCHAR2(20)         NOT NULL,
    BILTL                 VARCHAR2(20)         NOT NULL,
    BILFX                 VARCHAR2(20)         NOT NULL,
    ACTNO                 NUMBER(8, 0)     NOT NULL,
    ACTNM                 VARCHAR2(30)         NOT NULL,
    ACTA1                 VARCHAR2(25)         NOT NULL,
    ACTA2                 VARCHAR2(25)         NOT NULL,
    ACTA3                 VARCHAR2(25)         NOT NULL,
    ACTCT                 VARCHAR2(3)          NOT NULL,
    ACTAA                 VARCHAR2(10)         NOT NULL,
    SUPCD                 VARCHAR2(15)         NOT NULL,
    PYTRM                 VARCHAR2(30)         NOT NULL,
    FRTST                 NUMBER(1, 0)     NOT NULL,
    TRTRM                 VARCHAR2(30)         NOT NULL,
    DELPT                 VARCHAR2(15)         NOT NULL,
    PRTRM                 VARCHAR2(3)          NOT NULL,
    BNKNM                 VARCHAR2(25)         NOT NULL,
    BNKA1                 VARCHAR2(25)         NOT NULL,
    BNKA2                 VARCHAR2(25)         NOT NULL,
    BNKA3                 VARCHAR2(25)         NOT NULL,
    BNKNO                 VARCHAR2(15)         NOT NULL,
    INVNC                 VARCHAR2(20)         NOT NULL,
    INVPT                 VARCHAR2(20)         NOT NULL,
    INVAM                 NUMBER(13, 2)    NOT NULL,
    CURCD                 VARCHAR2(2)          NOT NULL,
    CURDC                 VARCHAR2(3)          NOT NULL,
    TAXAM                 NUMBER(13, 2)    NOT NULL,
    TAXPC                 NUMBER(5, 2)     NOT NULL,
    INSAM                 NUMBER(13, 2)    NOT NULL,
    FRGHT                 NUMBER(13, 2)    NOT NULL,
    SBLNO                 NUMBER(8, 0)     NOT NULL,
    SBLNM                 VARCHAR2(30)         NOT NULL,
    SBLA1                 VARCHAR2(25)         NOT NULL,
    SBLA2                 VARCHAR2(25)         NOT NULL,
    SBLA3                 VARCHAR2(25)         NOT NULL,
    SBLCT                 VARCHAR2(3)          NOT NULL,
    SBLAA                 VARCHAR2(10)         NOT NULL,
    SBLNC                 VARCHAR2(20)         NOT NULL,
    SBLDP                 VARCHAR2(20)         NOT NULL,
    SBLTL                 VARCHAR2(20)         NOT NULL,
    SBLFX                 VARCHAR2(20)         NOT NULL,
    SACNO                 NUMBER(8, 0)     NOT NULL,
    SACNM                 VARCHAR2(30)         NOT NULL,
    SACA1                 VARCHAR2(25)         NOT NULL,
    SACA2                 VARCHAR2(25)         NOT NULL,
    SACA3                 VARCHAR2(25)         NOT NULL,
    SACCT                 VARCHAR2(3)          NOT NULL,
    SACAA                 VARCHAR2(10)         NOT NULL,
    SSPCD                 VARCHAR2(15)         NOT NULL,
    SPYTM                 VARCHAR2(30)         NOT NULL,
    SFRST                 NUMBER(1, 0)     NOT NULL,
    STRTM                 VARCHAR2(30)         NOT NULL,
    SDLPT                 VARCHAR2(15)         NOT NULL,
    SPRTM                 VARCHAR2(3)          NOT NULL,
    SBKNM                 VARCHAR2(25)         NOT NULL,
    SBKA1                 VARCHAR2(25)         NOT NULL,
    SBKA2                 VARCHAR2(25)         NOT NULL,
    SBKA3                 VARCHAR2(25)         NOT NULL,
    SBKNO                 VARCHAR2(15)         NOT NULL,
    SINVC                 VARCHAR2(20)         NOT NULL,
    SIVPT                 VARCHAR2(20)         NOT NULL,
    SIVAM                 NUMBER(13, 2)    NOT NULL,
    SCRCD                 VARCHAR2(2)          NOT NULL,
    SCRDC                 VARCHAR2(3)          NOT NULL,
    STXAM                 NUMBER(13, 2)    NOT NULL,
    STXPC                 NUMBER(5, 2)     NOT NULL,
    SINAM                 NUMBER(13, 2)    NOT NULL,
    SFRGT                 NUMBER(13, 2)    NOT NULL,
    REGISTERED_AT         DATE             NOT NULL,
    REGISTERED_COMPNAME   VARCHAR2(50)     NOT NULL,
    REGISTERED_COMPCODE   VARCHAR2(50)     NOT NULL
);
