--------------------------------------------------------
--  File created - Tuesday-May-06-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table QRSHIPPINGLOG
--------------------------------------------------------

  CREATE TABLE "DSYNC"."QRSHIPPINGLOG" 
   (	"SEQ" NUMBER, 
	"WH" VARCHAR2(50 BYTE), 
	"DEVID" VARCHAR2(50 BYTE), 
	"SYSFLG1" VARCHAR2(20 BYTE), 
	"SYSFLG2" VARCHAR2(20 BYTE), 
	"SYSFLG3" VARCHAR2(20 BYTE), 
	"SYSFLG4" VARCHAR2(20 BYTE), 
	"LOGINID" VARCHAR2(25 BYTE), 
	"TRDATE" DATE, 
	"TRTYPE" NUMBER, 
	"OPESEQ" VARCHAR2(25 BYTE), 
	"RESULT" VARCHAR2(25 BYTE), 
	"RSNCODE" VARCHAR2(25 BYTE), 
	"TRUCKNO" VARCHAR2(25 BYTE), 
	"CUSTNO" VARCHAR2(25 BYTE), 
	"SHIPPN" VARCHAR2(50 BYTE), 
	"SHIPQTY" NUMBER, 
	"TAGTYPE" VARCHAR2(25 BYTE), 
	"PN" VARCHAR2(50 BYTE), 
	"CUSTPN" VARCHAR2(25 BYTE), 
	"QTY" NUMBER, 
	"TAGSEQ" VARCHAR2(25 BYTE), 
	"SCANDATE" DATE, 
	"SCANTIME" VARCHAR2(20 BYTE), 
	"REGISTERED_AT" DATE DEFAULT SYSDATE, 
	"REGISTERED_COMPNAME" VARCHAR2(100 BYTE), 
	"REGISTERED_COMPCODE" VARCHAR2(50 BYTE), 
	"SHIPNO" VARCHAR2(25 BYTE), 
	"CHECKTYPE" VARCHAR2(20 BYTE), 
	"FILENAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATASYNC" ;

   COMMENT ON COLUMN "DSYNC"."QRSHIPPINGLOG"."TRDATE" IS 'format:YYYYMMDD';
   COMMENT ON COLUMN "DSYNC"."QRSHIPPINGLOG"."REGISTERED_AT" IS 'SysDate (Server time)';
   COMMENT ON COLUMN "DSYNC"."QRSHIPPINGLOG"."REGISTERED_COMPNAME" IS 'Fix value';
   COMMENT ON COLUMN "DSYNC"."QRSHIPPINGLOG"."REGISTERED_COMPCODE" IS 'Fix value';
  GRANT SELECT ON "DSYNC"."QRSHIPPINGLOG" TO "DENSO_IS";
  GRANT SELECT ON "DSYNC"."QRSHIPPINGLOG" TO "LTA_ADMIN";
  GRANT DELETE ON "DSYNC"."QRSHIPPINGLOG" TO "DSYNCAIES";
  GRANT INSERT ON "DSYNC"."QRSHIPPINGLOG" TO "DSYNCAIES";
  GRANT SELECT ON "DSYNC"."QRSHIPPINGLOG" TO "DSYNCAIES";
  GRANT UPDATE ON "DSYNC"."QRSHIPPINGLOG" TO "DSYNCAIES";
--------------------------------------------------------
--  Constraints for Table QRSHIPPINGLOG
--------------------------------------------------------

  ALTER TABLE "DSYNC"."QRSHIPPINGLOG" MODIFY ("REGISTERED_AT" NOT NULL ENABLE);
  ALTER TABLE "DSYNC"."QRSHIPPINGLOG" MODIFY ("REGISTERED_COMPNAME" NOT NULL ENABLE);
  ALTER TABLE "DSYNC"."QRSHIPPINGLOG" MODIFY ("REGISTERED_COMPCODE" NOT NULL ENABLE);
