--------------------------------------------------------
--  File created - Tuesday-May-06-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CONFIGURATION
--------------------------------------------------------

  CREATE TABLE "DSYNC"."CONFIGURATION" 
   (	"CONFIG_NAME" VARCHAR2(100 BYTE), 
	"CONFIG_VALUE" VARCHAR2(100 BYTE), 
	"CREATED_DATE" DATE DEFAULT SYSDATE, 
	"UPDATED_DATE" DATE DEFAULT SYSDATE, 
	"CONFIG_TYPE" VARCHAR2(200 BYTE), 
	"DESCRIPTION" VARCHAR2(2000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATASYNC" ;

   COMMENT ON COLUMN "DSYNC"."CONFIGURATION"."CONFIG_TYPE" IS 'Configuration Type ex. EMAIL';
   COMMENT ON COLUMN "DSYNC"."CONFIGURATION"."DESCRIPTION" IS 'Description or instruction for this configuration';
  GRANT DELETE ON "DSYNC"."CONFIGURATION" TO "DSYNCAIES";
  GRANT INSERT ON "DSYNC"."CONFIGURATION" TO "DSYNCAIES";
  GRANT SELECT ON "DSYNC"."CONFIGURATION" TO "DSYNCAIES";
  GRANT UPDATE ON "DSYNC"."CONFIGURATION" TO "DSYNCAIES";
REM INSERTING into DSYNC.CONFIGURATION
SET DEFINE OFF;
Insert into DSYNC.CONFIGURATION (CONFIG_NAME,CONFIG_VALUE,CREATED_DATE,UPDATED_DATE,CONFIG_TYPE,DESCRIPTION) values ('LOG_DIR_NEXUS','D:\Aware-ETL\NEXUS\Logs',to_date('21-MAR-25','DD-MON-RR'),to_date('21-MAR-25','DD-MON-RR'),'NEXUS','ir for write the log file');
Insert into DSYNC.CONFIGURATION (CONFIG_NAME,CONFIG_VALUE,CREATED_DATE,UPDATED_DATE,CONFIG_TYPE,DESCRIPTION) values ('PURGE_DATA_DAYS_NEXUS','30',to_date('31-MAR-25','DD-MON-RR'),to_date('31-MAR-25','DD-MON-RR'),'NEXUS','Purge Data (Days)');
Insert into DSYNC.CONFIGURATION (CONFIG_NAME,CONFIG_VALUE,CREATED_DATE,UPDATED_DATE,CONFIG_TYPE,DESCRIPTION) values ('COMP_CODE_NEXUS','40040',to_date('31-MAR-25','DD-MON-RR'),to_date('31-MAR-25','DD-MON-RR'),'NEXUS','Compay Name');
Insert into DSYNC.CONFIGURATION (CONFIG_NAME,CONFIG_VALUE,CREATED_DATE,UPDATED_DATE,CONFIG_TYPE,DESCRIPTION) values ('COMP_NAME_NEXUS','DSTH',to_date('31-MAR-25','DD-MON-RR'),to_date('31-MAR-25','DD-MON-RR'),'NEXUS','Compay Code');
Insert into DSYNC.CONFIGURATION (CONFIG_NAME,CONFIG_VALUE,CREATED_DATE,UPDATED_DATE,CONFIG_TYPE,DESCRIPTION) values ('EMAIL_REC','kanjana.i@aware.co.th, wiriya.m@aware.co.th, pitchaya.i@aware.co.th',to_date('01-APR-25','DD-MON-RR'),to_date('01-APR-25','DD-MON-RR'),'EMAIL','List of Email Reciption for CIGMA');
Insert into DSYNC.CONFIGURATION (CONFIG_NAME,CONFIG_VALUE,CREATED_DATE,UPDATED_DATE,CONFIG_TYPE,DESCRIPTION) values ('EMAIL_SEND','AP_DIAT_DL@ap.denso.com',to_date('01-APR-25','DD-MON-RR'),to_date('01-APR-25','DD-MON-RR'),'EMAIL','Email Sender');
Insert into DSYNC.CONFIGURATION (CONFIG_NAME,CONFIG_VALUE,CREATED_DATE,UPDATED_DATE,CONFIG_TYPE,DESCRIPTION) values ('LOG_DIR_CIGMA','D:\Aware-ETL\CIGMA\Logs',to_date('04-APR-25','DD-MON-RR'),to_date('04-APR-25','DD-MON-RR'),'CIGMA','Dir for write the log file');
Insert into DSYNC.CONFIGURATION (CONFIG_NAME,CONFIG_VALUE,CREATED_DATE,UPDATED_DATE,CONFIG_TYPE,DESCRIPTION) values ('LOG_DIR_QR','D:\Aware-ETL\QR\Logs',to_date('09-APR-25','DD-MON-RR'),to_date('09-APR-25','DD-MON-RR'),'QR','Dir for write the log file');
Insert into DSYNC.CONFIGURATION (CONFIG_NAME,CONFIG_VALUE,CREATED_DATE,UPDATED_DATE,CONFIG_TYPE,DESCRIPTION) values ('COMP_CODE_QR','40040',to_date('21-MAR-25','DD-MON-RR'),to_date('21-MAR-25','DD-MON-RR'),'QR','Compay Code');
Insert into DSYNC.CONFIGURATION (CONFIG_NAME,CONFIG_VALUE,CREATED_DATE,UPDATED_DATE,CONFIG_TYPE,DESCRIPTION) values ('COMP_NAME_QR','DSTH',to_date('21-MAR-25','DD-MON-RR'),to_date('21-MAR-25','DD-MON-RR'),'QR','Compay Name');
Insert into DSYNC.CONFIGURATION (CONFIG_NAME,CONFIG_VALUE,CREATED_DATE,UPDATED_DATE,CONFIG_TYPE,DESCRIPTION) values ('PURGE_DATA_DAYS_QR','30',to_date('21-MAR-25','DD-MON-RR'),to_date('21-MAR-25','DD-MON-RR'),'QR','Purge Data (Days)');
Insert into DSYNC.CONFIGURATION (CONFIG_NAME,CONFIG_VALUE,CREATED_DATE,UPDATED_DATE,CONFIG_TYPE,DESCRIPTION) values ('COMP_CODE_CIGMA','40040',to_date('21-MAR-25','DD-MON-RR'),to_date('21-MAR-25','DD-MON-RR'),'CIGMA','Compay Code');
Insert into DSYNC.CONFIGURATION (CONFIG_NAME,CONFIG_VALUE,CREATED_DATE,UPDATED_DATE,CONFIG_TYPE,DESCRIPTION) values ('COMP_NAME_CIGMA','DSTH',to_date('21-MAR-25','DD-MON-RR'),to_date('21-MAR-25','DD-MON-RR'),'CIGMA','Compay Name');
Insert into DSYNC.CONFIGURATION (CONFIG_NAME,CONFIG_VALUE,CREATED_DATE,UPDATED_DATE,CONFIG_TYPE,DESCRIPTION) values ('PURGE_DATA_DAYS_CIGMA','30',to_date('21-MAR-25','DD-MON-RR'),to_date('21-MAR-25','DD-MON-RR'),'CIGMA','Purge Data (Days)');
--------------------------------------------------------
--  DDL for Index SYS_C008083
--------------------------------------------------------

  CREATE UNIQUE INDEX "DSYNC"."SYS_C008083" ON "DSYNC"."CONFIGURATION" ("CONFIG_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATASYNC" ;
--------------------------------------------------------
--  Constraints for Table CONFIGURATION
--------------------------------------------------------

  ALTER TABLE "DSYNC"."CONFIGURATION" MODIFY ("CONFIG_VALUE" NOT NULL ENABLE);
  ALTER TABLE "DSYNC"."CONFIGURATION" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "DSYNC"."CONFIGURATION" MODIFY ("UPDATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "DSYNC"."CONFIGURATION" ADD PRIMARY KEY ("CONFIG_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATASYNC"  ENABLE;
